version: "3.9"

services:
  web:
    build: .
    container_name: techcorp_web
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on: []
