name: Django CI/CD with Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: your-dockerhub-username/techcorp-app:latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Log in to Docker Hub (hardcoded credentials)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: your-dockerhub-username
        password: your-dockerhub-password-or-token

    # Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: ${{ env.DOCKER_IMAGE }}

    # Run Django tests inside Docker container
    - name: Run Django tests inside Docker
      run: |
        docker run --rm ${{ env.DOCKER_IMAGE }} python manage.py test performance

    # Push Docker image to Docker Hub
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE }}
